### ISSUE TITLE
purge is not working

### ISSUE THREAD

**Issue by gnkarn** [samccauley/addon-hassiogooglebackup#17]
the copy part is working fine , the purge is not working on the local hassio directory, nor on the google drive.

**Comment by BartEngelen** [comment]
Hello,
In my configuration the local purge is not working.
The Google purge is working fine with me.
Kind regards,
Bart

**Comment by samccauley** [comment]
@gnkarn For local hassio directory, if you're looking at your snapshots through the hassio UI, then make sure you're clicking on the refresh circle in the top-right corner. For google drive, keep in mind that the add-on can only delete files that it created itself.

**Comment by samccauley** [comment]
@BartEngelen For local hassio directory, if you're looking at your snapshots through the hassio UI, then make sure you're clicking on the refresh circle in the top-right corner.

**Comment by BartEngelen** [comment]
@samccauley I did that but it still remains in the folder.
When I delete it manually it goes away.
I will check this tomorrow when my backup plan runs again.
I will keep you inform about it.

**Comment by gnkarn** [comment]
i started all clean today, and it worked fine , not able to identify what changed , will see tomorrow what happened without touching anything and report back , tks

**Comment by BartEngelen** [comment]
The purge is not working for me anymore I get the followin error:
![image](https://user-images.githubusercontent.com/17978789/55386341-9699da80-552f-11e9-982c-e4ea22677d3a.png)

**Comment by BartEngelen** [comment]
Any update about this ?
Sometimes the purge is working but not everyday.

**Comment by samccauley** [comment]
The screenshot you gave is from Home Assistant and is too general to give me any helpful information. If I had to guess, I'd say you didn't have a long enough timeout set on your RESTful command. But since you don't give me any other information, I don't even know that you're using a Home Assistant RESTful command. Are you? Are you using a Home Assistant automation, perhaps? Still, all those things are Home Assistant features that I'm not very familiar with myself. The most helpful thing you could do would be to turn on debugging in the configuration of the add-on and then share the log file me when this error happens. The log file from my add-on is indeed something that I will be familiar with and may be able to use to help you.

If somehow I my wild guess about an insufficient time-out value is correct, please look at the README of the add-on for information about setting a timeout value on your RESTful command for calling the add-on's backup service.

**Comment by BartEngelen** [comment]
Yes I use the Home Assistant RESTful command.
![image](https://user-images.githubusercontent.com/17978789/55882409-caff3d80-5ba4-11e9-8ff5-c236e1eaad54.png)
I enabled the logging in the add-on I will add them here tomorrow after my automation trigger has ran tonight.
This is my automation trigger:
![image](https://user-images.githubusercontent.com/17978789/55882657-2fba9800-5ba5-11e9-9f5c-21f770aefd27.png)
And this is the sensor:
![image](https://user-images.githubusercontent.com/17978789/55882758-5678ce80-5ba5-11e9-8b51-669eb7b7512a.png)

**Comment by gnkarn** [comment]
reporting back , 
i have 2 instances of home assistant running on 2 VMs , both are performing backup on G.drive  at different moments, one is working fine ( just errors on the json  sensor received back , i need to dig into it . but the other just didnt work, while is configured the same way , on a different folder with different  folder  opaque code ,

i think , this is not working because i forgot to delete the  automated snapshot creation , right  ? - ( will test again later )

**Comment by gnkarn** [comment]
still not working  , here the logs  in case somebody may have a better idea of what could be going on
 `
INFO:oauth2client.client:Refreshing access_token
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1217, in _conn_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/googlebackup/gb/views.py", line 77, in doBackup
    backupResult = backupFiles(fromPattern, backupDirID, request.build_absolute_uri('/'))
  File "/googlebackup/gbcommon.py", line 255, in backupFiles
    if alreadyBackedUp(file, backupDirID, drive_service):
  File "/googlebackup/gbcommon.py", line 106, in alreadyBackedUp
    fields="files(id, name)").execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 837, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 162, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 186, in new_request
    credentials._refresh(orig_request_method)
  File "/usr/local/lib/python3.7/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/usr/local/lib/python3.7/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1226, in _conn_request
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 999, in connect
    address_info = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM)
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
INFO:root:googlebackup result: {'errorMessage': '[Errno -3] Try again'}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): hassio:80
DEBUG:urllib3.connectionpool:http://hassio:80 "POST /homeassistant/api/services/mqtt/publish HTTP/1.1" 200 2
DEBUG:root:<Response [200]>
Internal Server Error: /gb/doBackup
ERROR:django.request:Internal Server Error: /gb/doBackup
[11/Apr/2019 12:05:49] "GET /gb/doBackup HTTP/1.1" 500 40`

**Comment by BartEngelen** [comment]
Still not working for me I changed the timeout to 600.
Here are mine logs:

> DEBUG:root:backup fromPattern: /backup/*.tar
> DEBUG:root:backup backupDirID: _CODE_
> DEBUG:root:backup user_agent: http://xxx.xxx.xxx.xxx:8055/
> INFO:oauth2client.client:Refreshing access_token
> INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
> INFO:oauth2client.client:Refreshing access_token
> WARNING:googleapiclient._helpers:build() takes at most 2 positional arguments (3 given)
> INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
> INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/drive/v3/files?q=name%3D%271324e34e.tar%27+and+%27_CODE_%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json
> INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/drive/v3/files?q=name%3D%274b95136e.tar%27+and+%27_CODE_%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json
> INFO:root:Backing up /backup/4b95136e.tar to _CODE_
> DEBUG:root:drive_service = <googleapiclient.discovery.Resource object at 0x750c4c50>
> DEBUG:root:MIMETYPE = application/tar
> DEBUG:root:TITLE = Hassio Snapshot
> DEBUG:root:DESCRIPTION = Hassio Snapshot backup copy
> DEBUG:root:media_body: <googleapiclient.http.MediaFileUpload object at 0x750eb230>
> INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable
> ERROR:root:Traceback (most recent call last):
>   File "/googlebackup/gb/views.py", line 77, in doBackup
>     backupResult = backupFiles(fromPattern, backupDirID, request.build_absolute_uri('/'))
>   File "/googlebackup/gbcommon.py", line 263, in backupFiles
>     backupFile(file, backupDirID, drive_service, MIMETYPE, TITLE, DESCRIPTION)
>   File "/googlebackup/gbcommon.py", line 163, in backupFile
>     body=body, media_body=media_body).execute()
>   File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 813, in execute
>     _, body = self.next_chunk(http=http, num_retries=num_retries)
>   File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 974, in next_chunk
>     headers=headers)
>   File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 175, in new_request
>     redirections, connection_type)
>   File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
>     connection_type=connection_type)
>   File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1514, in request
>     (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
>   File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1264, in _request
>     (response, content) = self._conn_request(conn, request_uri, method, body, headers)
>   File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1188, in _conn_request
>     conn.request(method, request_uri, body, headers)
>   File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/local/lib/python3.7/http/client.py", line 1055, in _send_output
>     self.send(chunk)
>   File "/usr/local/lib/python3.7/http/client.py", line 977, in send
>     self.sock.sendall(data)
>   File "/usr/local/lib/python3.7/ssl.py", line 1015, in sendall
>     v = self.send(byte_view[count:])
>   File "/usr/local/lib/python3.7/ssl.py", line 984, in send
>     return self._sslobj.write(data)
> BrokenPipeError: [Errno 32] Broken pipe
> INFO:root:googlebackup result: {'errorMessage': '[Errno 32] Broken pipe'}
> DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): hassio:80
> DEBUG:urllib3.connectionpool:http://hassio:80 "POST /homeassistant/api/services/mqtt/publish HTTP/1.1" 200 2
> DEBUG:root:<Response [200]>
> Internal Server Error: /gb/doBackup
> ERROR:django.request:Internal Server Error: /gb/doBackup
> [12/Apr/2019 02:18:32] "GET /gb/doBackup HTTP/1.1" 500 42

**Comment by BartEngelen** [comment]
This can be closed it is working now.
I removed the add-on and installed it back and everything is ok now.
Thanks !
