### ISSUE TITLE
Unable to find the server at accounts.google.com

### ISSUE THREAD

**Issue by melojms** [samccauley/addon-hassiogooglebackup#25]
Plugin is not uploading backup file to google drive. Here is the log:

`Traceback (most recent call last):
  File "/googlebackup/gb/views.py", line 46, in doBackup
    backupResult = backupFiles(fromPattern, backupDirID, request.build_absolute_uri('/'))
  File "/googlebackup/gbcommon.py", line 154, in backupFiles
    drive_service = getDriveService(user_agent)
  File "/googlebackup/gbcommon.py", line 92, in getDriveService
    credentials.refresh(http)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/usr/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/lib/python3.6/site-packages/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/usr/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1194, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com
INFO:root:googlebackup result: {'errorMessage': 'Unable to find the server at accounts.google.com'}
ERROR:django.request:Internal Server Error: /gb/doBackup
[07/Aug/2019 03:00:05] "GET /gb/doBackup HTTP/1.1" 500 68`

**Comment by ildoddo** [comment]
Same problem here
