### ISSUE TITLE
Internal Server Error: /gb/adhocBackup

### ISSUE THREAD

**Issue by rock3r-swe** [samccauley/addon-hassiogooglebackup#31]
Trying to run adhocBackup but get 500 Internal Server error as a response.

**Stacktrace**
`INFO:oauth2client.client:Refreshing access_token
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
WARNING:googleapiclient._helpers:build() takes at most 2 positional arguments (3 given)
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/drive/v3/files?q=name%3D%27configuration.yaml%27+and+%_backupDirID_%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json
INFO:root:Deleted 0 files named configuration.yaml from Google Drive.
INFO:root:Backing up /config/configuration.yaml to _backupDirID_
ERROR:root:Traceback (most recent call last):
  File "/googlebackup/gb/views.py", line 49, in adhocBackup
    adhocBackupResult = adhocBackupFiles(fromPatterns, backupDirID, request.build_absolute_uri('/'))
  File "/googlebackup/gbcommon.py", line 225, in adhocBackupFiles
    backupFile(file, backupDirID, drive_service, MIMETYPE, TITLE, DESCRIPTION)
  File "/googlebackup/gbcommon.py", line 141, in backupFile
    logging.debug("MIMETYPE = " + MIMETYPE)
TypeError: can only concatenate str (not "NoneType") to str
INFO:root:googlebackup adhocBackup result: {'errorMessage': 'can only concatenate str (not "NoneType") to str'}
ERROR:django.request:Internal Server Error: /gb/adhocBackup`

**Comment by aramod** [comment]
Doesn't work on shared drives
