### ISSUE TITLE
NOT working Error executing service

### ISSUE THREAD

**Issue by gnkarn** [samccauley/addon-hassiogooglebackup#4]
it seams something is missing ,

installation and autentication goes fine , but the when executing the rest command is like it was inexistent .

here the logs

Error executing service <ServiceCall rest_command.google_backup (xxxxxxx)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/rest_command.py", line 103, in async_service_handler
    headers=headers
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 757, in start
    message, payload = await self._protocol.read()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 543, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/rest_command.py", line 116, in async_service_handler
    _LOGGER.error("Client error %s.", request.url)
UnboundLocalError: local variable 'request' referenced before assignment

**Comment by gnkarn** [comment]
after , long time diles started to apear on the drive , so it is uploading , but it does not execute the cleanup , nor on the source or destination .

logs , after configuration .

[12/Dec/2018 16:35:44] "GET /gb/ HTTP/1.1" 200 1296
[12/Dec/2018 16:35:45] "GET /favicon.ico HTTP/1.1" 404 85
[12/Dec/2018 16:35:51] "POST /gb/getAuth HTTP/1.1" 302 0
[12/Dec/2018 16:37:10] "POST /gb/authConfirmed HTTP/1.1" 200 1103
[12/Dec/2018 17:50:19] "GET /gb/doBackup HTTP/1.1" 500 288
