### ISSUE TITLE
Redirected but the response is missing a Location: header.

### ISSUE THREAD

**Issue by Smandurlo** [samccauley/addon-hassiogooglebackup#43]
Not sure what it means, I got this error.
Nothing changed. I tried to redo the installation from the beginning, but it didn't help.

"Redirected but the response is missing a Location: header"

ERROR:root:Traceback (most recent call last):
  File "/googlebackup/gb/views.py", line 98, in doBackup
    fromPattern, backupDirID, request.build_absolute_uri("/")
  File "/googlebackup/gbcommon.py", line 316, in backupFiles
    backupFile(file, backupDirID, drive_service, MIMETYPE, TITLE, DESCRIPTION)
  File "/googlebackup/gbcommon.py", line 199, in backupFile
    new_file = drive_service.files().create(body=body, media_body=media_body).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 871, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 1046, in next_chunk
    self.resumable_uri, method="PUT", body=data, headers=headers
  File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1709, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1448, in _request
    _("Redirected but the response is missing a Location: header."), response, content,
httplib2.error.RedirectMissingLocation: Redirected but the response is missing a Location: header.
INFO:root:googlebackup result: {'errorMessage': 'Redirected but the response is missing a Location: header.'}
ERROR:django.request:Internal Server Error: /gb/doBackup

**Comment by samccauley** [comment]
@Smandurlo Sorry about that. I just put a fix out there.

**Comment by Smandurlo** [comment]
Sorry? No need to :-) You are making a great addon for all of us! Thanks, I upgraded it and now it works flawless as before!

**Comment by sashayohan** [comment]
It stopped working, also gives this error

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
GB_DEBUG = false
GB_VERSION = 1.7.10
[2021-07-01 16:23:49 +0300] [205] [INFO] Starting gunicorn 19.9.0
[2021-07-01 16:23:49 +0300] [205] [INFO] Listening at: http://0.0.0.0:8000 (205)
[2021-07-01 16:23:49 +0300] [205] [INFO] Using worker: gevent
[2021-07-01 16:23:49 +0300] [207] [INFO] Booting worker with pid: 207
INFO:root:No local_settings to import
INFO:oauth2client.client:Refreshing access_token
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
WARNING:googleapiclient._helpers:build() takes at most 2 positional arguments (3 given)
INFO:root:Backing up /backup/fe108951.tar to 123a2kCGVX3a2kEJOEJObCGVX3a2kEJObCGVX
ERROR:root:Traceback (most recent call last):
  File "/googlebackup/gb/views.py", line 98, in doBackup
    fromPattern, backupDirID, request.build_absolute_uri("/")
  File "/googlebackup/gbcommon.py", line 316, in backupFiles
    backupFile(file, backupDirID, drive_service, MIMETYPE, TITLE, DESCRIPTION)
  File "/googlebackup/gbcommon.py", line 199, in backupFile
    new_file = drive_service.files().create(body=body, media_body=media_body).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 899, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 1078, in next_chunk
    self.resumable_uri, method="PUT", body=data, headers=headers
  File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1709, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1448, in _request
    _("Redirected but the response is missing a Location: header."), response, content,
httplib2.error.RedirectMissingLocation: Redirected but the response is missing a Location: header.
INFO:root:googlebackup result: {'errorMessage': 'Redirected but the response is missing a Location: header.'}
ERROR:django.request:Internal Server Error: /gb/doBackup
